### ISSUE TITLE
是否可以支持，给定一个方法，返回这个方法的调用链

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#13]
测试的时候，技术方案写了我改了XX方法，去看这部分代码的时候，能知道需要测一些场景
但是不敢确定其他场景是否会受影响，如果能知道更改的这个方法的往上以及往下的调用链，感觉应该会好一些

**Comment by uniquetruth** [comment]
你的思维方向可能错了，工具给出的调用链是根据你的测试操作统计出来的，如果单论一处代码的修改的话，由于没有测试操作，所以也就根本没有调用链。也许有静态代码扫描工具可以做到你说的这个效果，但我不知道。
或者你可以换个角度思考这个问题，假设过去你有一些丰富的测试案例，每个案例在执行的时候你都把它每一步的调用链记录下来，比如存到了数据库里。那么当前技术方案写了修改了xx方法，你就可以从数据库里查询到其影响范围。
