### ISSUE TITLE
TraceVo里没有class名，如何从method里提取出class名？

### ISSUE THREAD

**Issue by znifeng** [uniquetruth/remote-debug-agent#15]

**Comment by uniquetruth** [comment]
可尝试使用以下正则表达式来提取类名
```java
Pattern classNameExtra = Pattern.compile("\\s(.+?)\\.[^\\.]+?\\(");
Matcher m = classNameExtra.matcher(method);
if(m.find()) {
    return m.group(1);
}
```

**Comment by znifeng** [comment]
同一个类的多个method coverage，是如何去merge的？

**Comment by uniquetruth** [comment]
工具api并未提供获取一个类的覆盖率的功能。需要自行解析覆盖率结果文件才可获得。覆盖率结果文件中有3个对象，调用方法表: Map<String, Set<String>> methodMap，方法行号表: Map<String, ArrayList<Integer>> methodsLine，覆盖率表: Map<String, boolean[]> methodCover。  
首先确定你要统计的调用者ip，methodMap.get(ip)可得到该调用者执行过的所有方法集合，用正则表达式过滤出你关注的类的所有方法，然后集合methodsLine和methodCover即可得到这个类被执行了哪几行代码。  
注意这3个类在内存中不与写入磁盘时完全一样，若想自己开发接口操作这3个map的话，建议看看CoverageSnapshot类再动手
