### ISSUE TITLE
启动参数中增加-javaagent:${目录}/remote-debug-agent.jar，访问接口时报错java.util.ArrayList cannot be cast to feign.template.HeaderTemplate，不加启动参数正常

### ISSUE THREAD

**Issue by haohongbin** [uniquetruth/remote-debug-agent#2]

**Comment by uniquetruth** [comment]
似乎是springcloud-openfeign 2.X使用的header是Collection类型，3.X换成了feign.template.HeaderTemplate了，我会尽快修改以支持3.X的header，谢谢提醒。

**Comment by uniquetruth** [comment]
fixed by b25983db14016701cc43d6ec2405299e1c13dc51
请使用最新的master分支代码，或release v0.0.6
