### ISSUE TITLE
访问/trace/list没有任何返回

### ISSUE THREAD

**Issue by mxian** [uniquetruth/remote-debug-agent#21]
我是不是打开方式不对？

java -javaagent启动也成功了，start也看到start了，调了接口以后，访问trace/list，没看到任何返回

**Comment by mxian** [comment]
springboot的可以使用吗

**Comment by uniquetruth** [comment]
springboot一般是可以使用的，如果底层用的是tomcat或者jetty这样的通用技术的话。

trace/list接口没有返回的话，请核对一下includes的包前缀是否匹配你业务接口调用的代码。另外也可以描述一下你的网络环境，有可能是复杂的网络环境导致调用者绑定出了问题

**Comment by mxian** [comment]
> 

嗯，解决了，是我自己的问题。再想问一下，list出来了以后，如果想得到像jacoco那种html report，是不是得自己写代码来用模板替换？

**Comment by uniquetruth** [comment]
list接口接口得到的结果是用于调试的，虽然理论上它也是覆盖率的数据，但设计上不是的。想要得到html的报告请参考wiki中关于测试覆盖率的专门页面
