### ISSUE TITLE
你好，能支持访问常用中间件的数据吗

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#22]
中间件:  redis , es ，rocketMQ
比如  点个按钮，执行到某个方法，此方法访问到了redis，从redis获取到了什么值，或者往redis写了啥
再比如，点击某个按钮，执行到某个方法，此往消息队列写了数据，或者从消息队列读了数据
不知道我说明白没有

**Comment by uniquetruth** [comment]
你说清楚了，可是我对redis和es没什么研究，确实提供不了此方面的支持。
MQ的话之前考虑过支持rabbitMQ，不过后来觉得本身MQ这种东西就是异步的，调用链的使用场景基本还是基于同步调用才有意义，所以就没有做。
如果你或者周围的人有能力也可以fork我的项目做开发，我可以提供agent方面的咨询和支持。

**Comment by yang-yao** [comment]
好的，多谢啦
