### ISSUE TITLE
热卸载/detach有时候会失败

### ISSUE THREAD

**Issue by znifeng** [uniquetruth/remote-debug-agent#23]
![image](https://user-images.githubusercontent.com/10667015/232719885-a0faabf7-9e1a-4f13-9a54-4cce463d239f.png)

**Comment by znifeng** [comment]
此外，还有一个问题，就热卸载后，重新执行热加载命令的时候，会提示8098端口已经被占用

**Comment by uniquetruth** [comment]
我用最新版本的代码无法复现此问题。
请在最新版本下尝试以下操作看看：
1、cd agent
2、gradle runWebApp，该命令会启动项目自带的test程序，会启动一个java进程提供Http服务
3、打开浏览器，访问`http://localhost:8098/manage/detach`，向测试程序中的探针发送热卸载请求
4、查看agent目录下的test.log，它是测试应用的控制台日志，看是否会出现以上报错

PS. 可以发送`http://localhost:8080/stopserver` 请求关闭测试进程

**Comment by uniquetruth** [comment]
另外可以在报错行之前加这两句日志，看看detach的时候是什么值
System.out.println("this.classloader="+this.getClass().getClassLoader());
System.out.println("AsmTransformer.classloader="+AgentOptions.getTransformer().getClass().getClassLoader());

**Comment by uniquetruth** [comment]
因没有更进一步的信息，暂且关闭，如有需要可以重新打开
