### ISSUE TITLE
怎么从众多的调用链中快速定位到出问题的方法

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#24]
目前发现如果应用代码有bug，去查看调用链的时候，由于调用链可能会有很多条记录，可能有的记录很长，要找到出问题的方法，花费时间比较多，在这些很多很长的调用链中怎么快速定位到出问题的代码？ 大佬有啥建议吗

**Comment by uniquetruth** [comment]
首先人工的分析方法没有什么好说的，就是根据报错堆栈去找相关的调用链，很长的话也就只能一个一个找了。其次在谈到提高效率的话题时，无非是要把你人工的分析行为变成一些软件辅助的行为，这跟用nodepad写代码慢，所以需要IDE是一个道理了。
一些商业的调用链分析工具无非就是我这个东西加了一个调用链分析的客户端，所以要说经验的话，也只能借鉴这些去实现自己的客户端了。我的这个工程还处于工具这个层级，还没到解决方案的层级，所以相当于只实现了服务端，客户端是需要使用者自己实现的。

**Comment by yang-yao** [comment]
明白了，谢谢大佬
