### ISSUE TITLE
是否支持应用间的调用链收集？

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#25]
比如  app1和app2都注入了agent，且app1和app2通过dubbo实现调用
测试A  点了按钮 ButtonA，走到app1 （ip1）和 app2  (ip2)
收集调用链的时候  http://ip:8098/trace/list 这里的ip是ip1吗？ 貌似也不对，不知道怎么收集应用间的调用链
请指点

顺便弱弱问一下，为啥不把 jetty 和 asm的jar包一起打进agent.jar

**Comment by uniquetruth** [comment]
测试A点了按钮，那应该是用A这台机器的ip去查trace接口。dobbo2、3我应该都支持了，如果发现没有起效的话，最好再详细排查一下，比如看看app1的其它功能是否确实适配本探针，或者与dubbo相关的功能有没有做了什么特殊的架构之类的。

>顺便弱弱问一下，为啥不把 jetty 和 asm的jar包一起打进agent.jar  

打包基本是个人习惯吧，我不喜欢做一个大jar包。而且本工具作为一个开源软件，还是想尽量使自身和关联工具的关系体现得更清晰一些，以方便别人借鉴、研究。

**Comment by yang-yao** [comment]
多谢大佬
