### ISSUE TITLE
加了 lombok @Data的类，配置在excludes，没有被排除

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#27]
java -javaagent:/Users/yy/Downloads/code/accurate/remote-debug-agent-master/agent/build/libs/agent.jar=includes=com.yy.*,excludes=@Data,apiport=8098 -jar...

@Data
public class ProjectInfo implements Serializable {
。。。。
}

<img width="876" alt="image" src="https://user-images.githubusercontent.com/23271776/236629686-96d27130-0094-488f-b633-9962e958955b.png">
日志打印如下，按道理这里不应该打印出这个类，这个类加了@Data应该被过滤掉了
AppHandler.process.className：com/yy/commitdiff/domain/ProjectInfo

可能就如你之前所说，@Data注解生命周期是source，导致不会生效

![image](https://user-images.githubusercontent.com/23271776/236630131-f9ebce72-4081-4ec0-b11c-0f066ba6cb09.png)

**Comment by uniquetruth** [comment]
是的，lombok是通过注解处理器的形式在编译阶段工作的，应该是编译之后不会把注解的信息再带入到class文件里。感谢你的验证与分享。
