### ISSUE TITLE
关于dubbo的rpc调用疑问

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#29]
流程：服务器111(consumer)接受http请求，请求处理过程中RPC到服务器222(provider)
在consumer和provider都 注入了agent   agent参数：/agent.jar=includes=com.yy.*,apiport=8778
发请求到服务器111(consumer)模拟测试
接着获取trace/list，返回结果只包含了consumer的执行链路，没有provider的执行链路
 

注：我没有通过ip进行标识，是通过在http请求头里写入了标识比如name=zhangsan。发请求模拟测试
http请求（请求头带标识A）访问服务器111被拦截，建立线程A和标识A的绑定关系，dubbo client 根据线程A获取到标识，写入setAttachment，dubbo 服务端（服务器222）从getAttachment获取到标识A，用自己的线程B和标识A的建立绑定关系，
然后发请求去服务器111获取trace/list，为啥服务器222的代码链路没有在trace/list中，trace/list中只有服务器111的链路

**Comment by uniquetruth** [comment]
目前这个工具还不具备聚合多应用的调用链的特性。主要是因为整体的解决方案可能并不是agent能单独解决的问题，所以我尚未考虑过这个功能

**Comment by yang-yao** [comment]
ok  ，已经很棒了
所以，如果我要拿到服务器222的调用链路，就需要在服务器222上进行 trace/start 和 trace/list
