### ISSUE TITLE
覆盖率数据 怎么查看

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#3]
你好，感谢你的开源项目，我试用了一下，有2点
1. 就发了一个请求，操作了几次数据库，调用链数据太大了，看了很费劲，set,get 这些感觉不是太重要
2. 生成的 覆盖率数据  2022_07_31_10_49_25_318.cover 怎么查看，只能看到map数据吗，这样的话看起来也很费劲

**Comment by uniquetruth** [comment]
感谢使用。  
1. 点一个按钮调用成千上万个方法是很常见的情况，你可以把我的工具想象成服务端（S端），我只想提供S端的功能，你如果想要从这些海量的数据中提取你关心的部分，那么你可能需要自己实现一点客户端（B端）的东西。目前我不打算提供任何B端的实现，但我很乐意在这方面给他人提供帮助。
> 另外你可以尝试在javaagent的参数中尽量精确的配置你需要关心的代码范围，wiki中有配置手册。比如你不想看get、set方法的话，可以把pojo类配置到例外范围中。  
2. 关于覆盖率，wiki中有一个页面尽量详细的描述了其内容。不知你有没有看到该页面，如果已经看了，且依然解决不了你的需要的话，我近期也正在写一个专门关于覆盖率统计的文章，但因为覆盖率毕竟不是这个工具的核心内容，所以会发布到别的地方（可能一两周内）。届时我会把链接贴到本issue下，请持续关注。

**Comment by yang-yao** [comment]
感谢耐心回复，nice
明白了！！！

**Comment by uniquetruth** [comment]
关于测试覆盖率的[完整文章](http://testerhome.com/topics/34038)  
本问题我就先关闭了，如有其它具体问题请新开issue
