### ISSUE TITLE
执行trace/list, 数据为空并报错

### ISSUE THREAD

**Issue by Mrshenxh** [uniquetruth/remote-debug-agent#33]
<img width="1019" alt="image" src="https://github.com/uniquetruth/remote-debug-agent/assets/50947635/dc779b6c-3a55-4df6-a76e-1a24e457db73">

**Comment by uniquetruth** [comment]
从日志来看这是一个debug级别的报错，并且是可以ignored的。此外堆栈里全是jetty的代码，与本工程没有关系。
至于list接口返回为空的问题，推测与这个报错没有必然联系。请提供更多信息或重新确认一下javaagent的配置以及你的目标业务代码是否理论上能被agent处理到

**Comment by Mrshenxh** [comment]
误报，我这边换了应用，忘了改includes了。。。
大佬厉害👍
