### ISSUE TITLE
关于项目中的三方包插桩问题

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#5]
目前插桩的时候 通过includes=com.yangao.* 来收集这个包下调用链数据，
如果公司中对比如 zk,dubbo,redis 进行了封装也是用 com.yangyao.*来作为包名，
项目中用到这些会通过maven 进行依赖，那么 是否也会收集maven依赖包的调用链
说白了就是  项目的包名跟三方依赖包名一样，会不会也收集到依赖包的调用链

**Comment by uniquetruth** [comment]
会，javaagent是作用于jvm的，只要是这个jvm里被加载的类就遵循其影响规则。这个时候就必须使用excludes对其进行排除
