### ISSUE TITLE
关于注入后 RPC 报错问题

### ISSUE THREAD

**Issue by yang-yao** [uniquetruth/remote-debug-agent#9]
agent注入了项目，然后没有发送 trace/list  ，直接去页面操作，报错，抓包发现 RPC其他服务的接口报错
No provider available from registry   其他服务不在注册中心
取消注入，又正常了

**Comment by uniquetruth** [comment]
请提供更多信息
1. 添加了agent的是客户端还是服务端？
2. 是客户端报错还是服务端报错?
3. 是应用启动时报错，还是发送请求时报错，还是处理请求时报错？
4. 报错应用的日志堆栈尽量提供一下

**Comment by yang-yao** [comment]
稍等我再验证验证，我发现不是必现

**Comment by uniquetruth** [comment]
如有更多信息请提交新issue
